### ISSUE TITLE
Watch OS 9 Beta: Couldn't establish connection to MQTT server, getting connection timeout error

### ISSUE THREAD

**Issue by umasankar421** [swift-server-community/mqtt-nio#121]
**Describe the bug**
Getting Connection timeout error when try to establish the connection to MQTT server in Apple watch. but its working fine in WatchOS simulator. I am using WatchOS 9 beta 5.
I tried with 30 sec of connection timeout, still no use. 

```swift
MQTTClient(host: url.host ?? "",
    port: url.port,
    identifier: clientId,
    eventLoopGroupProvider: .createNew,
    configuration: .init(version: .v3_1_1,
    keepAliveInterval: .seconds(10),
    connectTimeout: .seconds(30),
    useSSL: true,
    useWebSockets: true,
    tlsConfiguration: .ts(.init(certificateVerification: .fullVerification)),
    webSocketURLPath: "\(url.path)?\(url.query ?? "")"))
```
Seeing this below error in the log
**connection error connectTimeout(NIOCore.TimeAmount(nanoseconds: 10000000000))**

**Expected behavior**
Connection establish should happen between client and MQTT server in Watch OS 9 beta in a real watch.

**Context (please complete the following information):**
 - Platform : WatchOS
 - Swift/Xcode Version: Xcode 14 beta 5
 - Version : WatchOS 9 beta 5

**Comment by adam-fowler** [comment]
Do you know if this works with watchOS8?
Also could you test if you can attach to the mosquito test server from your Apple Watch. Use client with these settings
```swift
let client = MQTTClient(
    host: "test.mosquitto.org",
    port: 1883,
    identifier: "watchTestConnection",
    eventLoopGroupProvider: .createNew
)
```

**Comment by umasankar421** [comment]
Thanks for the reply @adam-fowler 
This works fine in WatchOS 8. seeing this issue in WatchOS 9 beta only.
I will try for this mosquito test server and update here.

**Comment by umasankar421** [comment]
@adam-fowler 
Tested with above mosquito test server from my Apple watch. Seeing same issue like below

**connection error connectTimeout(NIOCore.TimeAmount(nanoseconds: 10000000000))**

However, above test server is working fine on a watchOS 9 simulator.

**Comment by adam-fowler** [comment]
OK, I don't have an Apple watch. So it is going to be hard for me to work out what is going on, but I imagine this is some issue between `swift-nio` and the new watchOS. We could try to see if other `swift-nio` based projects work on your watch. [AsyncHTTPClient](https://github.com/swift-server/async-http-client) is the swift on server standard HTTP client. If you could try to use that to on your watch it could point to `swift-nio` being the culprit. They have simple sample code to load a web page

```swift
import AsyncHTTPClient

let httpClient = HTTPClient(eventLoopGroupProvider: .createNew)

/// MARK: - Using Swift Concurrency
let request = HTTPClientRequest(url: "https://apple.com/")
let response = try await httpClient.execute(request, timeout: .seconds(30))
print("HTTP head", response)
if response.status == .ok {
    let body = try await response.body.collect(upTo: 1024 * 1024) // 1 MB
    // handle body
} else {
    // handle remote error
}
```

**Comment by umasankar421** [comment]
@adam-fowler 
Seeing similar behavior with this [AsyncHTTPClient](https://github.com/swift-server/async-http-client) also.
It is working on Apple watch simulator but not working on Actual Apple Watch.

So like you mentioned, this is issue with `swift-nio`.

**Comment by adam-fowler** [comment]
It is pointing to an issue with `swift-nio` and watchOS 9 beta. It is probably best to add an issue to the `swift-nio` repository.
