### ISSUE TITLE
Publication preconditions

### ISSUE THREAD

**Issue by Dev1an** [swift-server-community/mqtt-nio#128]
**Context:**
Suppose you want to respond to a message that was published via MQTT. Then you would probably need to write something like:
```swift
let client = MQTTClient(
    host: someHost,
    identifier: someID,
    eventLoopGroupProvider: .createNew
)
// ... subscription code left out ... \\
client.addPublishListener(named: someName) { potentialPublication in
    do {
        let someResponse = process(try potentialPublication.get())
        client.publish(to: someDestination, payload: someResponse, qos: .atLeastOnce)
    } catch {
        print(error)
    }
}
```

The problem with that code of course is that we have a [strong reference cycle](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html#ID51). The client is holding a reference to itself inside the PublishListener. One way to get around the cycle would be to add `[unowned client]` to the listener but this will crash if a client would be destroyed just before or during the execution of the listener. Hence the following question.

**Question:**
When you add a PublishListener using [addPublishListener(named:listener:)](https://swift-server-community.github.io/mqtt-nio/documentation/mqttnio/mqttclient/addpublishlistener(named:_:)), is there a guarantee that the `MQTTClient` that received the `Result<MQTTPublishInfo, Error>` still exists when the `listener` is executed?

**Comment by adam-fowler** [comment]
Yes.

The publish listeners are owned by the MQTTClient and are only ever accessed via the client. So the client needs to exist for a listener to be called.

**Comment by Dev1an** [comment]
OK thanks for the quick reply. So that means that I can safely use `[unowned client]`? like this:
```swift
client.addPublishListener(named: someName) { [unowned client] p in
   client.publish(to: someDestination, payload: someResponse, qos: .atLeastOnce)
}
```

**Comment by adam-fowler** [comment]
Yes that should work. Although I have just added #129 which clears the listener array in the shutdown and thus removes the reference cycle

**Comment by adam-fowler** [comment]
This is in the latest release https://github.com/swift-server-community/mqtt-nio/releases/tag/2.7.1
