### ISSUE TITLE
Doubt: Timeouts when connecting, subscribing, and unsubscribing

### ISSUE THREAD

**Issue by ruijfcanas** [swift-server-community/mqtt-nio#136]
Hello!

I'm currently working on a project where I'm using mqtt-nio, and I've encountered something that it's not really a bug but it's making my logs kind of messy. I keep getting timeout errors whenever I try to connect, subscribe, or unsubscribe using the library. The funny thing about it is that, despite these timeouts, I get to subscribe and receive all the content as expected.

I've double-checked my code, and it seems to be correct. I'm using the last version of the library. I'm wondering if anyone has any insights on what might be causing these timeouts.

<details>
<summary>🪵 My logs</summary>

```
[CustomMqttClient.connect() :93]: [APP-MQTT] Connect with error. - timeout
[CustomMqttClient.subscribe() :153]: [APP-MQTT] Subscribe with error. - timeout
INFO KMM-MQTT - MQTT Client subscribed into my/shared/test!
INFO KMM-MQTT - MQTT Client published into my/shared/test!
DEBUG KMM-MQTT - on topic my/shared/test received message: Hello from my topic
INFO KMM-MQTT - MQTT Client unsubscribed into my/shared /test!
[CustomMattClient.unsubscribe():1681: [APP-MQTT] Unsubscribe with error. - timeout
```
</details>

<details>
<summary>🔍 Implementation</summary>
This is how I'm implementing the connect and it's pretty much the same for the rest.

```
do {
     _ = try await client.connect(cleanSession: isCleanStart, will: will).get()
} catch {
     log.info("\(Tags.mqtt) Connect with error. - \(error)")
}
```
</details>

Thanks in advance!

**Comment by adam-fowler** [comment]
Are you setting the timeout value in the configuration for `MQTTClient`. Could you post the code where you create your client? You get a timeout when the ack response is not received from the server in time after sending a connect, subscribe, publish etc. The message has still been sent, so the server could receive the message but just not respond in time.

Have you tried connecting to a test server to see if your server is the issue. You can setup up a locally running test server using the shell script `./script/mosquitto.sh`. You can then connect to host:localhost, port:1883.

**Comment by ruijfcanas** [comment]
I gave it a second look on the way I was doing the configuration and the issue was exactly that. I wasn't giving enough time to receive the ack response and adding a little bit of time was what I needed to avoid having the timeout logs!

Thank you for the quick feedback!
