### ISSUE TITLE
V2.9.0 causes CLIENT_ERROR disconnect from AWS shadow, but v2.7.0 does not

### ISSUE THREAD

**Issue by FleetPhil** [swift-server-community/mqtt-nio#144]
Any attempt to interact with a device shadow (/get or /update) on AWS using 2.9.0 causes AWS failure then disconnect. CloudWatch events on 2.9.0 are:

```
{
    "timestamp": "2023-11-01 17:23:10.204",
    "logLevel": "ERROR",
    "traceId": "cf60a0d1-ead7-f46d-f59b-04697613200a",
    "accountId": "278277519326",
    "status": "Failure",
    "eventType": "Publish-In",
    "protocol": "MQTT",
    "topicName": "$aws/things/garage/shadow/get",
    "clientId": "428193CD-1C8E-4816-B54F-32961E24FEEA",
    "principalId": "39cbc03c728823970a5337a3b44f33c5199db91312e5f1eb977a4dcc5c0edcac",
    "sourceIp": "5.80.44.51",
    "sourcePort": 40538
}

{
    "timestamp": "2023-11-01 17:23:10.218",
    "logLevel": "INFO",
    "traceId": "75ab78e9-ee42-f044-2187-8d9a97dfaae2",
    "accountId": "278277519326",
    "status": "Success",
    "eventType": "Disconnect",
    "protocol": "MQTT",
    "clientId": "428193CD-1C8E-4816-B54F-32961E24FEEA",
    "principalId": "39cbc03c728823970a5337a3b44f33c5199db91312e5f1eb977a4dcc5c0edcac",
    "sourceIp": "5.80.44.51",
    "sourcePort": 40538,
    "disconnectReason": "CLIENT_ERROR"
}
```

No issues with connection, just update. Reverting to 2.7.0 with otherwise completely identical code (so no policy issues) is successful:

```
{
    "timestamp": "2023-11-01 17:45:54.750",
    "logLevel": "INFO",
    "traceId": "893ab84d-79fa-9acf-fd66-d4beb1d18c09",
    "accountId": "278277519326",
    "status": "Success",
    "eventType": "Publish-In",
    "protocol": "MQTT",
    "topicName": "$aws/things/garage/shadow/get",
    "clientId": "03E7BABE-66C0-4F05-91AE-83649D608256",
    "principalId": "39cbc03c728823970a5337a3b44f33c5199db91312e5f1eb977a4dcc5c0edcac",
    "sourceIp": "5.80.44.51",
    "sourcePort": 58412
}
``` 

Code is Swift Swift version 5.9 (swift-5.9-RELEASE) on Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1041-raspi aarch64)

**Comment by adam-fowler** [comment]
Are you able to narrow the version a little more. Does it work with v2.8.0?
How are you connecting to your MQTT server? WebSocket or a X.509 certificate
Is this disconnecting on a publish event? Are you able to show the code that is causing the disconnect?
Does it disconnect on all messages?
Could you enable trace logging on the client and attach a log here?

**Comment by FleetPhil** [comment]
Thanks for the quick response! Answers are...

I've checked and it fails on 2.8.0 as well
I'm connecting using X.509 (certificate generated by AWS)
It's failing on all the publish calls that I have tried, my code is:
```
    func publish(message: IoTMessage) async throws {
        
        if debug { print("AWSIoTInterface: publish: \(message)") }

        if !client.isActive() {
            if debug { print("AWSIoTInterface: reconnecting") }

            _ = try await connect()
            
            if debug { print("AWSIoTInterface: reconnected") }

        }

        do {
            try await client.publish(to: message.topic.value,
                                      payload: ByteBufferAllocator().buffer(string: message.payload ?? ""),
                                      qos: .atLeastOnce,
                                      retain: true)
        } catch {
            print("Publish failed with error: \(error)")
            throw error
        }
        
        if debug { print("AWSIoTInterface: published") }

    }
```
resulting in:
```
AWSIoTInterface: publish: IoTMessage(topic: AWSIoT.Topic(value: "$aws/things/garage/shadow/get"), payload: Optional(""))
Publish failed with error: serverClosedConnection
```
As well as the CloudWatch events above

My code fails on /get and /update messages, I've not tried any others.

By trace logging do you mean the <logger> parameter in the <MQTTClient> initialiser?   If so I don't think I can use that as I'm not running on an Apple platform, and I don't thing Logger is supported? Happy to run additional tracing if that is possible

**Comment by adam-fowler** [comment]
The only change I can see that might affect you is I fixed a bug where the retain flag was not passed on. Does your code work if you set this to false?

**Comment by adam-fowler** [comment]
Another question. Could it be the combination of publishing an empty message with the retain flag set that is causing the disconnect.

**Comment by adam-fowler** [comment]
> By trace logging do you mean the parameter in the initialiser? If so I don't think I can use that as I'm not running on an Apple platform, and I don't thing Logger is supported? Happy to run additional tracing if that is possible

MQTTNIO uses swift-log for its logging. This can be given any backend to output it's logs. By default swift-log outputs to stdout. You just need to supply a `Logger` to the client at initialization.

```swift
var logger = Logger(label: "MQTT")
logger.logLevel = .trace
let mqttClient = MQTTClient(...
    logger: logger
)
```

**Comment by FleetPhil** [comment]
It's not related to the empty payload as the disconnect also happens on a shadow update with a payload. I saw that the only relevant change from 2.7 to 2.8 was the retain flag on publish so I'll try changing that...

**Comment by FleetPhil** [comment]
Thanks for your help! Changing the retain flag to false fixes it. Tested on 2.8.0 and 2.9.0 with and without payload...
