### ISSUE TITLE
Cannot establish a connection on real watch device but simulator works find.

### ISSUE THREAD

**Issue by freyzou** [swift-server-community/mqtt-nio#155]
**Describe the bug**
All works find on watch simulator, but failed to  connect on real watch device.

**To Reproduce**
Build a solely watch app, try to connect a broke.

**Expected behavior**
Connection can established and communication can work.

**Context (please complete the following information):**
 - Platform [watchOS 10.0]
 - Swift/Xcode Version:5.8
 - Version [2.0.0]

**Additional context**

**Comment by adam-fowler** [comment]
See https://github.com/apple/swift-nio/issues/2255
