### ISSUE TITLE
test certificates are expired

### ISSUE THREAD

**Issue by jpgrayson** [swift-server-community/mqtt-nio#156]
**Describe the bug**

The test certificates found in `mosquitto/certs/` are expired. This causes the three SSL-related tests in the test suite to fail.

```
Test Case '-[MQTTNIOTests.MQTTNIOTests testSSLConnect]' started.
/Users/runner/work/mqtt-nio/mqtt-nio/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:1039: error: -[MQTTNIOTests.MQTTNIOTests testSSLConnect] : failed: caught error: "connectTimeout(NIOCore.TimeAmount(nanoseconds: 10000000000))"
Test Case '-[MQTTNIOTests.MQTTNIOTests testSSLConnect]' failed (10.402 seconds).
Test Case '-[MQTTNIOTests.MQTTNIOTests testSSLConnectFromP12]' started.
/Users/runner/work/mqtt-nio/mqtt-nio/.build/checkouts/swift-nio/Sources/NIOCore/EventLoopFuture.swift:1039: error: -[MQTTNIOTests.MQTTNIOTests testSSLConnectFromP12] : failed: caught error: "connectTimeout(NIOCore.TimeAmount(nanoseconds: 10000000000))"
Test Case '-[MQTTNIOTests.MQTTNIOTests testSSLConnectFromP12]' failed (10.129 seconds).
...
Received: Hello
Trust failed: “soto.codes” certificate is expired
Trust failed: “soto.codes” certificate is expired
Trust failed: “soto.codes” certificate is expired
```

**To Reproduce**

`swift test --filter testSSLConnect --filter testWebsocketAndSSLConnect`

**Expected behavior**

Tests should pass.

**Context (please complete the following information):**

This issue presents on MacOS and in the Linux CI environment.

**Additional context**

I believe @adam-fowler may be the only person that is able to generate the new certs. My naive attempt to run `scripts/generate-certs.sh` myself results in more abrupt SSL connection failures.

I would like to update the CI test matrix to include Swift 6.0, which is how I bumped into this problem.

**Comment by adam-fowler** [comment]
Not sure why'd it be just me that can generate the certificates. I'll have a look into it and try and make sure anyone can generate the certificates.

**Comment by jpgrayson** [comment]
My initial attempt to generate certs was using a version of openssl installed by homebrew.

I tried again, adjusting `PATH`, to use the MacOS provided `/usr/bin/openssl`. This has better results. Tests pass.

So I can post a PR with new certs if that's alright.
